version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '2345:5432'
    volumes:
      - './scripts/init:/docker-entrypoint-initdb.d'
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
