trader:
  tinkoffInvestApi:
    token: ${TINKOFF_TOKEN:token}
server:
  port: 8081
spring:
  datasource:
    url: "jdbc:postgresql://localhost:2345/trader"
    username: postgres
    password: postgres
  flyway:
    schemas: trader
